updated static-classes
SteamDeckHomebrew/decky-frontend-lib pull request #26
Opened 2022-09-24 15:55 UTC by Tormak9970

Fixed bugs with old implementation and added a more future-proof solution. Also added alias ScollPanelClasses for ScrollClasses as that is the name of the component

2022-09-24 17:47 UTC, AAGaming00 requested changes

2022-09-24 17:47 UTC, AAGaming00 commented on src/deck-components/static-classes.ts
> +export const scrollPanelClasses = scrollClasses;
Please switch this around, the incorrect one should be an alias and marked with // @deprecated

Would also appreciate if you could do the same with staticClasses

2022-09-29 13:21 UTC, Tormak9970 commented
Been busy. Gonna finish this up later today

2022-10-02 01:31 UTC, AAGaming00 approved these changes

2022-10-02 01:32 UTC, merged