feat(steam-utils): add initial utils for Steam-related API
SteamDeckHomebrew/decky-frontend-lib pull request #48
Opened 2022-11-01 19:58 UTC by FrogTheFrog

2022-12-11 20:01 UTC, AAGaming00 requested changes

2022-12-12 13:24 UTC, AAGaming00 commented on src/steam-utils/restartSteamClient.ts
> +    console.error(error);
Under what condition would startrestart throw?

2022-12-12 13:25 UTC, FrogTheFrog commented on src/steam-utils/restartSteamClient.ts
> +    console.error(error);
When the API is removed from `SteamClient.User` and moved somewhere else

2022-12-12 13:36 UTC, AAGaming00 commented on src/steam-utils/restartSteamClient.ts
> +    console.error(error);
yeah ok we don't need to account for that with a trycatch as we would then have to do so for everything

doubt they're gonna move steamclient stuff that is this old

2022-12-12 13:37 UTC, FrogTheFrog commented on src/steam-utils/restartSteamClient.ts
> +    console.error(error);
In other cases I do need to account for it (where it returns bool), so that I can clean up, just so you know.

2022-12-15 12:08 UTC, AAGaming00 approved these changes

2023-02-18 18:54 UTC, FrogTheFrog commented
Closing due to unknown status and it also needs to be updated due to Valve breaking everything...

2023-02-18 18:54 UTC, closed without merging