Steam client reference
SteamDeckHomebrew/decky-frontend-lib pull request #92
Opened 2023-08-27 11:09 UTC by FlashyReese

Using the SDH Discord server, GitHub, and personal findings, I have attempted to document as many functions as possible within the `SteamClient` object. Feedback is greatly appreciated. If you come across any functions that are not documented and you already understand their purpose, please consider leaving a comment or suggestion.

**To-Do List:**
- [ ] Verify the functionality of all documented functions.
- [ ] Organize and restructure all the interfaces for better readability.

2023-09-22 16:58 UTC, AAGaming00 commented
After reading the latest commit message, how are you detecting the interface changes so quickly?

2023-09-22 18:03 UTC, AAGaming00 commented
That's awesome, I'll add this to my update diff system if you don't mind

2023-09-22 18:26 UTC, FlashyReese commented
I think we can write a tool to generate the aforementioned TypeScript interfaces from it. This could prove useful, as it can be utilized anywhere. Unfortunately, native code does not provide parameters for these functions. This means documenting parameters must be done manually, unless someone is aware of a method I am not familiar with.

2023-11-18 13:30 UTC, PartyWumpus commented
> 
> Edit: I decided to spend some time and write one: https://gist.github.com/FlashyReese/05748e25b9feabe14e62ef873a8058cb

Noticed you weren't able to get the name of the object from the object. If it's a global object then this should work `Object.getOwnPropertyNames(window).filter(name => window[name] === obj)[0]`. Probably not actually useful though.

2024-06-27 03:20 UTC, AAGaming00 commented
is this ready for review yet? (at least to have it merged until we can have this as a separate package)

2024-06-27 03:20 UTC, AAGaming00 commented
Also please retarget to v4-dev

2024-06-29 14:08 UTC, FlashyReese commented
I've rebased to the `v4-dev` branch. This should be ready for review.

2024-10-17 13:53 UTC, KP2048 commented
@PartyWumpus @FlashyReese is this ready for merge yet?

2024-10-17 14:14 UTC, PartyWumpus commented
@AAGaming00 wanted to review it first I think

2024-10-17 14:18 UTC, KP2048 commented
Yeah it's just been sitting here and it would be more useful if it was actually merged lol

2024-11-05 04:51 UTC, snowkat commented
Looks like `Apps.SetShortcutExe` is defined in main but not this PR, is that intentional?

I also noticed a dozen or so other methods that are missing from both main and this PR. I'm assuming they were intentionally skipped (mostly `RegisterFor[...]`), but for the sake of completeness, here they are: https://gist.github.com/snowkat/2a60138a4a67bc4342787383c3c9ccd4

Checked on Steam versions 1726683985 and 1730512277.

2024-11-20 16:09 UTC, ricewind012 commented
> Looks like `Apps.SetShortcutExe` is defined in main but not this PR, is that intentional?
> 
> I also noticed a dozen or so other methods that are missing from both main and this PR. I'm assuming they were intentionally skipped (mostly `RegisterFor[...]`), but for the sake of completeness, here they are: https://gist.github.com/snowkat/2a60138a4a67bc4342787383c3c9ccd4
> 
> Checked on Steam versions 1726683985 and 1730512277.

just missed, thanks for the list

2025-04-23 12:03 UTC, AAGaming00 requested changes
pls move out of deck-components these aren't components, then ill merge

otherwise lgtm, left a few comments but not strict requirements

we're considering forming a team to maintain these in the future (possibly in a separate package) so this doesn't happen again, send me a dm over on discord (or an email if you can't) if you're interested

thank you for being patient <3

2025-04-23 12:04 UTC, AAGaming00 commented
also please document any tooling used in creating and maintaining these on the wiki when you can

2025-04-23 12:19 UTC, ricewind012 commented on src/deck-components/steam-client/Parental.ts
> +    enabled_features?: number;
it's a number, so im not sure if i should, see https://github.com/SteamDatabase/SteamTracking/blob/0769e24d4a92f590ff369ad737cf5c11eb85d214/Protobufs/steammessages_parental_objects.proto#L38

2025-04-23 12:20 UTC, ricewind012 commented on src/deck-components/steam-client/User.ts
> +            emailDomain: string,
so do i just remove the note ?

2025-04-23 12:25 UTC, ricewind012 commented on src/deck-components/steam-client/WebChat.ts
> +     * @todo Does not actually show the dialog.
not broken anymore

2025-04-23 12:29 UTC, ricewind012 commented on src/deck-components/steam-client/RemotePlay.ts
> +    // TODO: -1 no preference? no idea where the settings are anyway lol
doesn't show on neither host nor client advanced options even while connected, hence the "no idea where the settings are"

2025-04-23 12:31 UTC, ricewind012 commented on src/deck-components/steam-client/browser-view/BrowserViewPopup.ts
> +    OpenDevTools = 26500,
i wrote that like 1.5 years ago, not sure what it is anymore lol

2025-04-23 12:31 UTC, ricewind012 commented on src/deck-components/steam-client/WebChat.ts
> +    // Opens the URL in default web browser, despite what the name says ?
right, it does

2025-04-23 12:31 UTC, ricewind012 commented on src/deck-components/steam-client/Screenshots.ts
> +    strCaption: '';
fixed

2025-04-23 12:35 UTC, AAGaming00 commented on src/deck-components/steam-client/browser-view/BrowserViewPopup.ts
> +    OpenDevTools = 26500,
nah just valve being valve

2025-04-23 12:36 UTC, AAGaming00 commented on src/deck-components/steam-client/Parental.ts
> +    enabled_features?: number;
i trust your judgement

2025-04-23 12:36 UTC, AAGaming00 commented on src/deck-components/steam-client/User.ts
> +            emailDomain: string,
IMO remove todo but keep note

2025-04-23 14:08 UTC, ricewind012 commented on src/deck-components/steam-client/User.ts
> +            emailDomain: string,
kept

2025-04-23 14:17 UTC, AAGaming00 commented
redo the move commit using git mv pls

2025-04-23 14:47 UTC, ricewind012 commented
i don't know git but i hope it's fine now 😭

2025-04-23 14:52 UTC, AAGaming00 commented
> i don't know git but i hope it's fine now 😭
history is still messed up since u just reverted the commit instead of removing it
use git reset to revert to the commit before you moved them, then use git mv

2025-04-23 15:01 UTC, ricewind012 commented
> git reset

oh, like that, then git push --force ? it's the only way i know of removing commits but i always saw that it's a bad idea, etc. etc... im asking since i don't want to mess it up any further

2025-04-23 15:08 UTC, AAGaming00 commented
yep force push

2025-04-23 15:16 UTC, AAGaming00 approved these changes

2025-04-23 15:20 UTC, merged